// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8lPbesecs7vnvSscJs1VDqGapojv4mus',
    appId: '1:310787575736:web:3567851cbbc2f8645c094d',
    messagingSenderId: '310787575736',
    projectId: 'project2-c2fe8',
    authDomain: 'project2-c2fe8.firebaseapp.com',
    storageBucket: 'project2-c2fe8.firebasestorage.app',
    measurementId: 'G-0WMQB94F5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFeqzF4cJshEa8r8QQxokpYvt56eDLk8Y',
    appId: '1:310787575736:android:18d70f48dc7d58005c094d',
    messagingSenderId: '310787575736',
    projectId: 'project2-c2fe8',
    storageBucket: 'project2-c2fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcq_3Mipmnk1xGPQwKxlKXIfoshvFvCmo',
    appId: '1:310787575736:ios:b43e7423faf643bd5c094d',
    messagingSenderId: '310787575736',
    projectId: 'project2-c2fe8',
    storageBucket: 'project2-c2fe8.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcq_3Mipmnk1xGPQwKxlKXIfoshvFvCmo',
    appId: '1:310787575736:ios:b43e7423faf643bd5c094d',
    messagingSenderId: '310787575736',
    projectId: 'project2-c2fe8',
    storageBucket: 'project2-c2fe8.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8lPbesecs7vnvSscJs1VDqGapojv4mus',
    appId: '1:310787575736:web:f7340c2664c28aab5c094d',
    messagingSenderId: '310787575736',
    projectId: 'project2-c2fe8',
    authDomain: 'project2-c2fe8.firebaseapp.com',
    storageBucket: 'project2-c2fe8.firebasestorage.app',
    measurementId: 'G-66SLED29LK',
  );
}
